# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
### Build Stage
FROM golang:1.24-alpine AS builder

# Install git for go mod and make
RUN apk add --no-cache git make

WORKDIR /app

# Copy go modules files
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the server binary
RUN make build

### Final Stage
FROM alpine:latest

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/cmd/server/unsplash-mcp-server ./unsplash-mcp-server

# Expose any necessary port if applicable (not strictly needed for MCP server over stdio)
# EXPOSE 8080

# Set entrypoint to the server binary
ENTRYPOINT ["./unsplash-mcp-server"]
